// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: grpc_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GRPCInferenceService_Infer_FullMethodName        = "/inference.GRPCInferenceService/Infer"
	GRPCInferenceService_InferStream_FullMethodName  = "/inference.GRPCInferenceService/InferStream"
	GRPCInferenceService_FetchInfer_FullMethodName   = "/inference.GRPCInferenceService/FetchInfer"
	GRPCInferenceService_SendResponse_FullMethodName = "/inference.GRPCInferenceService/SendResponse"
)

// GRPCInferenceServiceClient is the client API for GRPCInferenceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GRPCInferenceServiceClient interface {
	Infer(ctx context.Context, in *InferRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InferResponse], error)
	InferStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[InferRequest, InferResponse], error)
	FetchInfer(ctx context.Context, in *FetchInferRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FetchInferResponse], error)
	SendResponse(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SendResponseRequest, emptypb.Empty], error)
}

type gRPCInferenceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGRPCInferenceServiceClient(cc grpc.ClientConnInterface) GRPCInferenceServiceClient {
	return &gRPCInferenceServiceClient{cc}
}

func (c *gRPCInferenceServiceClient) Infer(ctx context.Context, in *InferRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InferResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GRPCInferenceService_ServiceDesc.Streams[0], GRPCInferenceService_Infer_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InferRequest, InferResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GRPCInferenceService_InferClient = grpc.ServerStreamingClient[InferResponse]

func (c *gRPCInferenceServiceClient) InferStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[InferRequest, InferResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GRPCInferenceService_ServiceDesc.Streams[1], GRPCInferenceService_InferStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InferRequest, InferResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GRPCInferenceService_InferStreamClient = grpc.BidiStreamingClient[InferRequest, InferResponse]

func (c *gRPCInferenceServiceClient) FetchInfer(ctx context.Context, in *FetchInferRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FetchInferResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GRPCInferenceService_ServiceDesc.Streams[2], GRPCInferenceService_FetchInfer_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FetchInferRequest, FetchInferResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GRPCInferenceService_FetchInferClient = grpc.ServerStreamingClient[FetchInferResponse]

func (c *gRPCInferenceServiceClient) SendResponse(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SendResponseRequest, emptypb.Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GRPCInferenceService_ServiceDesc.Streams[3], GRPCInferenceService_SendResponse_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SendResponseRequest, emptypb.Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GRPCInferenceService_SendResponseClient = grpc.ClientStreamingClient[SendResponseRequest, emptypb.Empty]

// GRPCInferenceServiceServer is the server API for GRPCInferenceService service.
// All implementations should embed UnimplementedGRPCInferenceServiceServer
// for forward compatibility.
type GRPCInferenceServiceServer interface {
	Infer(*InferRequest, grpc.ServerStreamingServer[InferResponse]) error
	InferStream(grpc.BidiStreamingServer[InferRequest, InferResponse]) error
	FetchInfer(*FetchInferRequest, grpc.ServerStreamingServer[FetchInferResponse]) error
	SendResponse(grpc.ClientStreamingServer[SendResponseRequest, emptypb.Empty]) error
}

// UnimplementedGRPCInferenceServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGRPCInferenceServiceServer struct{}

func (UnimplementedGRPCInferenceServiceServer) Infer(*InferRequest, grpc.ServerStreamingServer[InferResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Infer not implemented")
}
func (UnimplementedGRPCInferenceServiceServer) InferStream(grpc.BidiStreamingServer[InferRequest, InferResponse]) error {
	return status.Errorf(codes.Unimplemented, "method InferStream not implemented")
}
func (UnimplementedGRPCInferenceServiceServer) FetchInfer(*FetchInferRequest, grpc.ServerStreamingServer[FetchInferResponse]) error {
	return status.Errorf(codes.Unimplemented, "method FetchInfer not implemented")
}
func (UnimplementedGRPCInferenceServiceServer) SendResponse(grpc.ClientStreamingServer[SendResponseRequest, emptypb.Empty]) error {
	return status.Errorf(codes.Unimplemented, "method SendResponse not implemented")
}
func (UnimplementedGRPCInferenceServiceServer) testEmbeddedByValue() {}

// UnsafeGRPCInferenceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GRPCInferenceServiceServer will
// result in compilation errors.
type UnsafeGRPCInferenceServiceServer interface {
	mustEmbedUnimplementedGRPCInferenceServiceServer()
}

func RegisterGRPCInferenceServiceServer(s grpc.ServiceRegistrar, srv GRPCInferenceServiceServer) {
	// If the following call pancis, it indicates UnimplementedGRPCInferenceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GRPCInferenceService_ServiceDesc, srv)
}

func _GRPCInferenceService_Infer_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InferRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GRPCInferenceServiceServer).Infer(m, &grpc.GenericServerStream[InferRequest, InferResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GRPCInferenceService_InferServer = grpc.ServerStreamingServer[InferResponse]

func _GRPCInferenceService_InferStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GRPCInferenceServiceServer).InferStream(&grpc.GenericServerStream[InferRequest, InferResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GRPCInferenceService_InferStreamServer = grpc.BidiStreamingServer[InferRequest, InferResponse]

func _GRPCInferenceService_FetchInfer_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FetchInferRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GRPCInferenceServiceServer).FetchInfer(m, &grpc.GenericServerStream[FetchInferRequest, FetchInferResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GRPCInferenceService_FetchInferServer = grpc.ServerStreamingServer[FetchInferResponse]

func _GRPCInferenceService_SendResponse_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GRPCInferenceServiceServer).SendResponse(&grpc.GenericServerStream[SendResponseRequest, emptypb.Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GRPCInferenceService_SendResponseServer = grpc.ClientStreamingServer[SendResponseRequest, emptypb.Empty]

// GRPCInferenceService_ServiceDesc is the grpc.ServiceDesc for GRPCInferenceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GRPCInferenceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inference.GRPCInferenceService",
	HandlerType: (*GRPCInferenceServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Infer",
			Handler:       _GRPCInferenceService_Infer_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "InferStream",
			Handler:       _GRPCInferenceService_InferStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "FetchInfer",
			Handler:       _GRPCInferenceService_FetchInfer_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SendResponse",
			Handler:       _GRPCInferenceService_SendResponse_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "grpc_service.proto",
}
