// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: grpc_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InferResponse_Status int32

const (
	InferResponse_UNKNOWN    InferResponse_Status = 0
	InferResponse_ACK        InferResponse_Status = 1
	InferResponse_PROCESSING InferResponse_Status = 2
	InferResponse_FINISH     InferResponse_Status = 3
	InferResponse_ERROR      InferResponse_Status = 4
)

// Enum value maps for InferResponse_Status.
var (
	InferResponse_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "ACK",
		2: "PROCESSING",
		3: "FINISH",
		4: "ERROR",
	}
	InferResponse_Status_value = map[string]int32{
		"UNKNOWN":    0,
		"ACK":        1,
		"PROCESSING": 2,
		"FINISH":     3,
		"ERROR":      4,
	}
)

func (x InferResponse_Status) Enum() *InferResponse_Status {
	p := new(InferResponse_Status)
	*p = x
	return p
}

func (x InferResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InferResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_service_proto_enumTypes[0].Descriptor()
}

func (InferResponse_Status) Type() protoreflect.EnumType {
	return &file_grpc_service_proto_enumTypes[0]
}

func (x InferResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InferResponse_Status.Descriptor instead.
func (InferResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_grpc_service_proto_rawDescGZIP(), []int{5, 0}
}

type SendResponseRequest_Status int32

const (
	SendResponseRequest_PROCESSING SendResponseRequest_Status = 0
	SendResponseRequest_FINISH     SendResponseRequest_Status = 1
	SendResponseRequest_ERROR      SendResponseRequest_Status = 2
)

// Enum value maps for SendResponseRequest_Status.
var (
	SendResponseRequest_Status_name = map[int32]string{
		0: "PROCESSING",
		1: "FINISH",
		2: "ERROR",
	}
	SendResponseRequest_Status_value = map[string]int32{
		"PROCESSING": 0,
		"FINISH":     1,
		"ERROR":      2,
	}
)

func (x SendResponseRequest_Status) Enum() *SendResponseRequest_Status {
	p := new(SendResponseRequest_Status)
	*p = x
	return p
}

func (x SendResponseRequest_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SendResponseRequest_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_service_proto_enumTypes[1].Descriptor()
}

func (SendResponseRequest_Status) Type() protoreflect.EnumType {
	return &file_grpc_service_proto_enumTypes[1]
}

func (x SendResponseRequest_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SendResponseRequest_Status.Descriptor instead.
func (SendResponseRequest_Status) EnumDescriptor() ([]byte, []int) {
	return file_grpc_service_proto_rawDescGZIP(), []int{8, 0}
}

type ServerLiveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Live          bool                   `protobuf:"varint,1,opt,name=live,proto3" json:"live,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerLiveResponse) Reset() {
	*x = ServerLiveResponse{}
	mi := &file_grpc_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerLiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerLiveResponse) ProtoMessage() {}

func (x *ServerLiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerLiveResponse.ProtoReflect.Descriptor instead.
func (*ServerLiveResponse) Descriptor() ([]byte, []int) {
	return file_grpc_service_proto_rawDescGZIP(), []int{0}
}

func (x *ServerLiveResponse) GetLive() bool {
	if x != nil {
		return x.Live
	}
	return false
}

func (x *ServerLiveResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServerLiveResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type ServerLiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerLiveRequest) Reset() {
	*x = ServerLiveRequest{}
	mi := &file_grpc_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerLiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerLiveRequest) ProtoMessage() {}

func (x *ServerLiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerLiveRequest.ProtoReflect.Descriptor instead.
func (*ServerLiveRequest) Descriptor() ([]byte, []int) {
	return file_grpc_service_proto_rawDescGZIP(), []int{1}
}

type InferCore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         []byte                 `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferCore) Reset() {
	*x = InferCore{}
	mi := &file_grpc_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferCore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferCore) ProtoMessage() {}

func (x *InferCore) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferCore.ProtoReflect.Descriptor instead.
func (*InferCore) Descriptor() ([]byte, []int) {
	return file_grpc_service_proto_rawDescGZIP(), []int{2}
}

func (x *InferCore) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *InferCore) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ResponseCore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        []byte                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseCore) Reset() {
	*x = ResponseCore{}
	mi := &file_grpc_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseCore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseCore) ProtoMessage() {}

func (x *ResponseCore) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseCore.ProtoReflect.Descriptor instead.
func (*ResponseCore) Descriptor() ([]byte, []int) {
	return file_grpc_service_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseCore) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *ResponseCore) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type InferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Infer         *InferCore             `protobuf:"bytes,1,opt,name=infer,proto3" json:"infer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferRequest) Reset() {
	*x = InferRequest{}
	mi := &file_grpc_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferRequest) ProtoMessage() {}

func (x *InferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferRequest.ProtoReflect.Descriptor instead.
func (*InferRequest) Descriptor() ([]byte, []int) {
	return file_grpc_service_proto_rawDescGZIP(), []int{4}
}

func (x *InferRequest) GetInfer() *InferCore {
	if x != nil {
		return x.Infer
	}
	return nil
}

type InferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Response      *ResponseCore          `protobuf:"bytes,2,opt,name=response,proto3,oneof" json:"response,omitempty"`
	Status        *InferResponse_Status  `protobuf:"varint,3,opt,name=status,proto3,enum=inference.InferResponse_Status,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferResponse) Reset() {
	*x = InferResponse{}
	mi := &file_grpc_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferResponse) ProtoMessage() {}

func (x *InferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferResponse.ProtoReflect.Descriptor instead.
func (*InferResponse) Descriptor() ([]byte, []int) {
	return file_grpc_service_proto_rawDescGZIP(), []int{5}
}

func (x *InferResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *InferResponse) GetResponse() *ResponseCore {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *InferResponse) GetStatus() InferResponse_Status {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return InferResponse_UNKNOWN
}

type FetchInferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      map[string]string      `protobuf:"bytes,1,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchInferRequest) Reset() {
	*x = FetchInferRequest{}
	mi := &file_grpc_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchInferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchInferRequest) ProtoMessage() {}

func (x *FetchInferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchInferRequest.ProtoReflect.Descriptor instead.
func (*FetchInferRequest) Descriptor() ([]byte, []int) {
	return file_grpc_service_proto_rawDescGZIP(), []int{6}
}

func (x *FetchInferRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type FetchInferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Infer         *InferCore             `protobuf:"bytes,2,opt,name=infer,proto3" json:"infer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchInferResponse) Reset() {
	*x = FetchInferResponse{}
	mi := &file_grpc_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchInferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchInferResponse) ProtoMessage() {}

func (x *FetchInferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchInferResponse.ProtoReflect.Descriptor instead.
func (*FetchInferResponse) Descriptor() ([]byte, []int) {
	return file_grpc_service_proto_rawDescGZIP(), []int{7}
}

func (x *FetchInferResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *FetchInferResponse) GetInfer() *InferCore {
	if x != nil {
		return x.Infer
	}
	return nil
}

type SendResponseRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	RequestId     string                      `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Response      *ResponseCore               `protobuf:"bytes,2,opt,name=response,proto3,oneof" json:"response,omitempty"`
	Status        *SendResponseRequest_Status `protobuf:"varint,3,opt,name=status,proto3,enum=inference.SendResponseRequest_Status,oneof" json:"status,omitempty"`
	Metrics       map[string]string           `protobuf:"bytes,4,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponseRequest) Reset() {
	*x = SendResponseRequest{}
	mi := &file_grpc_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponseRequest) ProtoMessage() {}

func (x *SendResponseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponseRequest.ProtoReflect.Descriptor instead.
func (*SendResponseRequest) Descriptor() ([]byte, []int) {
	return file_grpc_service_proto_rawDescGZIP(), []int{8}
}

func (x *SendResponseRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SendResponseRequest) GetResponse() *ResponseCore {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *SendResponseRequest) GetStatus() SendResponseRequest_Status {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return SendResponseRequest_PROCESSING
}

func (x *SendResponseRequest) GetMetrics() map[string]string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

var File_grpc_service_proto protoreflect.FileDescriptor

const file_grpc_service_proto_rawDesc = "" +
	"\n" +
	"\x12grpc_service.proto\x12\tinference\x1a\x1bgoogle/protobuf/empty.proto\x1a\x19google/protobuf/any.proto\"^\n" +
	"\x12ServerLiveResponse\x12\x12\n" +
	"\x04live\x18\x01 \x01(\bR\x04live\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\"\x13\n" +
	"\x11ServerLiveRequest\"\x9e\x01\n" +
	"\tInferCore\x12\x14\n" +
	"\x05input\x18\x01 \x01(\fR\x05input\x12>\n" +
	"\bmetadata\x18\x02 \x03(\v2\".inference.InferCore.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa6\x01\n" +
	"\fResponseCore\x12\x16\n" +
	"\x06output\x18\x01 \x01(\fR\x06output\x12A\n" +
	"\bmetadata\x18\x02 \x03(\v2%.inference.ResponseCore.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\":\n" +
	"\fInferRequest\x12*\n" +
	"\x05infer\x18\x01 \x01(\v2\x14.inference.InferCoreR\x05infer\"\x85\x02\n" +
	"\rInferResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x128\n" +
	"\bresponse\x18\x02 \x01(\v2\x17.inference.ResponseCoreH\x00R\bresponse\x88\x01\x01\x12<\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1f.inference.InferResponse.StatusH\x01R\x06status\x88\x01\x01\"E\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\a\n" +
	"\x03ACK\x10\x01\x12\x0e\n" +
	"\n" +
	"PROCESSING\x10\x02\x12\n" +
	"\n" +
	"\x06FINISH\x10\x03\x12\t\n" +
	"\x05ERROR\x10\x04B\v\n" +
	"\t_responseB\t\n" +
	"\a_status\"\x98\x01\n" +
	"\x11FetchInferRequest\x12F\n" +
	"\bmetadata\x18\x01 \x03(\v2*.inference.FetchInferRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"_\n" +
	"\x12FetchInferResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12*\n" +
	"\x05infer\x18\x02 \x01(\v2\x14.inference.InferCoreR\x05infer\"\xfe\x02\n" +
	"\x13SendResponseRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x128\n" +
	"\bresponse\x18\x02 \x01(\v2\x17.inference.ResponseCoreH\x00R\bresponse\x88\x01\x01\x12B\n" +
	"\x06status\x18\x03 \x01(\x0e2%.inference.SendResponseRequest.StatusH\x01R\x06status\x88\x01\x01\x12E\n" +
	"\ametrics\x18\x04 \x03(\v2+.inference.SendResponseRequest.MetricsEntryR\ametrics\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"/\n" +
	"\x06Status\x12\x0e\n" +
	"\n" +
	"PROCESSING\x10\x00\x12\n" +
	"\n" +
	"\x06FINISH\x10\x01\x12\t\n" +
	"\x05ERROR\x10\x02B\v\n" +
	"\t_responseB\t\n" +
	"\a_status2\x86\x03\n" +
	"\x14GRPCInferenceService\x12K\n" +
	"\n" +
	"ServerLive\x12\x1c.inference.ServerLiveRequest\x1a\x1d.inference.ServerLiveResponse\"\x00\x12>\n" +
	"\x05Infer\x12\x17.inference.InferRequest\x1a\x18.inference.InferResponse\"\x000\x01\x12F\n" +
	"\vInferStream\x12\x17.inference.InferRequest\x1a\x18.inference.InferResponse\"\x00(\x010\x01\x12M\n" +
	"\n" +
	"FetchInfer\x12\x1c.inference.FetchInferRequest\x1a\x1d.inference.FetchInferResponse\"\x000\x01\x12J\n" +
	"\fSendResponse\x12\x1e.inference.SendResponseRequest\x1a\x16.google.protobuf.Empty\"\x00(\x01B(Z&github.com/anyserve/anyserve/pkg/protob\x06proto3"

var (
	file_grpc_service_proto_rawDescOnce sync.Once
	file_grpc_service_proto_rawDescData []byte
)

func file_grpc_service_proto_rawDescGZIP() []byte {
	file_grpc_service_proto_rawDescOnce.Do(func() {
		file_grpc_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_service_proto_rawDesc), len(file_grpc_service_proto_rawDesc)))
	})
	return file_grpc_service_proto_rawDescData
}

var file_grpc_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_grpc_service_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_grpc_service_proto_goTypes = []any{
	(InferResponse_Status)(0),       // 0: inference.InferResponse.Status
	(SendResponseRequest_Status)(0), // 1: inference.SendResponseRequest.Status
	(*ServerLiveResponse)(nil),      // 2: inference.ServerLiveResponse
	(*ServerLiveRequest)(nil),       // 3: inference.ServerLiveRequest
	(*InferCore)(nil),               // 4: inference.InferCore
	(*ResponseCore)(nil),            // 5: inference.ResponseCore
	(*InferRequest)(nil),            // 6: inference.InferRequest
	(*InferResponse)(nil),           // 7: inference.InferResponse
	(*FetchInferRequest)(nil),       // 8: inference.FetchInferRequest
	(*FetchInferResponse)(nil),      // 9: inference.FetchInferResponse
	(*SendResponseRequest)(nil),     // 10: inference.SendResponseRequest
	nil,                             // 11: inference.InferCore.MetadataEntry
	nil,                             // 12: inference.ResponseCore.MetadataEntry
	nil,                             // 13: inference.FetchInferRequest.MetadataEntry
	nil,                             // 14: inference.SendResponseRequest.MetricsEntry
	(*emptypb.Empty)(nil),           // 15: google.protobuf.Empty
}
var file_grpc_service_proto_depIdxs = []int32{
	11, // 0: inference.InferCore.metadata:type_name -> inference.InferCore.MetadataEntry
	12, // 1: inference.ResponseCore.metadata:type_name -> inference.ResponseCore.MetadataEntry
	4,  // 2: inference.InferRequest.infer:type_name -> inference.InferCore
	5,  // 3: inference.InferResponse.response:type_name -> inference.ResponseCore
	0,  // 4: inference.InferResponse.status:type_name -> inference.InferResponse.Status
	13, // 5: inference.FetchInferRequest.metadata:type_name -> inference.FetchInferRequest.MetadataEntry
	4,  // 6: inference.FetchInferResponse.infer:type_name -> inference.InferCore
	5,  // 7: inference.SendResponseRequest.response:type_name -> inference.ResponseCore
	1,  // 8: inference.SendResponseRequest.status:type_name -> inference.SendResponseRequest.Status
	14, // 9: inference.SendResponseRequest.metrics:type_name -> inference.SendResponseRequest.MetricsEntry
	3,  // 10: inference.GRPCInferenceService.ServerLive:input_type -> inference.ServerLiveRequest
	6,  // 11: inference.GRPCInferenceService.Infer:input_type -> inference.InferRequest
	6,  // 12: inference.GRPCInferenceService.InferStream:input_type -> inference.InferRequest
	8,  // 13: inference.GRPCInferenceService.FetchInfer:input_type -> inference.FetchInferRequest
	10, // 14: inference.GRPCInferenceService.SendResponse:input_type -> inference.SendResponseRequest
	2,  // 15: inference.GRPCInferenceService.ServerLive:output_type -> inference.ServerLiveResponse
	7,  // 16: inference.GRPCInferenceService.Infer:output_type -> inference.InferResponse
	7,  // 17: inference.GRPCInferenceService.InferStream:output_type -> inference.InferResponse
	9,  // 18: inference.GRPCInferenceService.FetchInfer:output_type -> inference.FetchInferResponse
	15, // 19: inference.GRPCInferenceService.SendResponse:output_type -> google.protobuf.Empty
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_grpc_service_proto_init() }
func file_grpc_service_proto_init() {
	if File_grpc_service_proto != nil {
		return
	}
	file_grpc_service_proto_msgTypes[5].OneofWrappers = []any{}
	file_grpc_service_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_service_proto_rawDesc), len(file_grpc_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_service_proto_goTypes,
		DependencyIndexes: file_grpc_service_proto_depIdxs,
		EnumInfos:         file_grpc_service_proto_enumTypes,
		MessageInfos:      file_grpc_service_proto_msgTypes,
	}.Build()
	File_grpc_service_proto = out.File
	file_grpc_service_proto_goTypes = nil
	file_grpc_service_proto_depIdxs = nil
}
