// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: grpc_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InferCore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferCore) Reset() {
	*x = InferCore{}
	mi := &file_grpc_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferCore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferCore) ProtoMessage() {}

func (x *InferCore) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferCore.ProtoReflect.Descriptor instead.
func (*InferCore) Descriptor() ([]byte, []int) {
	return file_grpc_service_proto_rawDescGZIP(), []int{0}
}

func (x *InferCore) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *InferCore) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type InferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Infer         *InferCore             `protobuf:"bytes,1,opt,name=infer,proto3" json:"infer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferRequest) Reset() {
	*x = InferRequest{}
	mi := &file_grpc_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferRequest) ProtoMessage() {}

func (x *InferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferRequest.ProtoReflect.Descriptor instead.
func (*InferRequest) Descriptor() ([]byte, []int) {
	return file_grpc_service_proto_rawDescGZIP(), []int{1}
}

func (x *InferRequest) GetInfer() *InferCore {
	if x != nil {
		return x.Infer
	}
	return nil
}

type InferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Response      *InferCore             `protobuf:"bytes,2,opt,name=response,proto3,oneof" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferResponse) Reset() {
	*x = InferResponse{}
	mi := &file_grpc_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferResponse) ProtoMessage() {}

func (x *InferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferResponse.ProtoReflect.Descriptor instead.
func (*InferResponse) Descriptor() ([]byte, []int) {
	return file_grpc_service_proto_rawDescGZIP(), []int{2}
}

func (x *InferResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *InferResponse) GetResponse() *InferCore {
	if x != nil {
		return x.Response
	}
	return nil
}

type FetchInferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      map[string]string      `protobuf:"bytes,1,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchInferRequest) Reset() {
	*x = FetchInferRequest{}
	mi := &file_grpc_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchInferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchInferRequest) ProtoMessage() {}

func (x *FetchInferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchInferRequest.ProtoReflect.Descriptor instead.
func (*FetchInferRequest) Descriptor() ([]byte, []int) {
	return file_grpc_service_proto_rawDescGZIP(), []int{3}
}

func (x *FetchInferRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type FetchInferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Infer         *InferCore             `protobuf:"bytes,2,opt,name=infer,proto3,oneof" json:"infer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchInferResponse) Reset() {
	*x = FetchInferResponse{}
	mi := &file_grpc_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchInferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchInferResponse) ProtoMessage() {}

func (x *FetchInferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchInferResponse.ProtoReflect.Descriptor instead.
func (*FetchInferResponse) Descriptor() ([]byte, []int) {
	return file_grpc_service_proto_rawDescGZIP(), []int{4}
}

func (x *FetchInferResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *FetchInferResponse) GetInfer() *InferCore {
	if x != nil {
		return x.Infer
	}
	return nil
}

type SendResponseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Response      *InferCore             `protobuf:"bytes,2,opt,name=response,proto3,oneof" json:"response,omitempty"`
	Metrics       map[string]string      `protobuf:"bytes,3,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponseRequest) Reset() {
	*x = SendResponseRequest{}
	mi := &file_grpc_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponseRequest) ProtoMessage() {}

func (x *SendResponseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponseRequest.ProtoReflect.Descriptor instead.
func (*SendResponseRequest) Descriptor() ([]byte, []int) {
	return file_grpc_service_proto_rawDescGZIP(), []int{5}
}

func (x *SendResponseRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SendResponseRequest) GetResponse() *InferCore {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *SendResponseRequest) GetMetrics() map[string]string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

var File_grpc_service_proto protoreflect.FileDescriptor

const file_grpc_service_proto_rawDesc = "" +
	"\n" +
	"\x12grpc_service.proto\x12\tinference\x1a\x1bgoogle/protobuf/empty.proto\x1a\x19google/protobuf/any.proto\"\xa2\x01\n" +
	"\tInferCore\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\x12>\n" +
	"\bmetadata\x18\x02 \x03(\v2\".inference.InferCore.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\":\n" +
	"\fInferRequest\x12*\n" +
	"\x05infer\x18\x01 \x01(\v2\x14.inference.InferCoreR\x05infer\"r\n" +
	"\rInferResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x125\n" +
	"\bresponse\x18\x02 \x01(\v2\x14.inference.InferCoreH\x00R\bresponse\x88\x01\x01B\v\n" +
	"\t_response\"\x98\x01\n" +
	"\x11FetchInferRequest\x12F\n" +
	"\bmetadata\x18\x01 \x03(\v2*.inference.FetchInferRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"n\n" +
	"\x12FetchInferResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12/\n" +
	"\x05infer\x18\x02 \x01(\v2\x14.inference.InferCoreH\x00R\x05infer\x88\x01\x01B\b\n" +
	"\x06_infer\"\xfb\x01\n" +
	"\x13SendResponseRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x125\n" +
	"\bresponse\x18\x02 \x01(\v2\x14.inference.InferCoreH\x00R\bresponse\x88\x01\x01\x12E\n" +
	"\ametrics\x18\x03 \x03(\v2+.inference.SendResponseRequest.MetricsEntryR\ametrics\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\v\n" +
	"\t_response2\xb9\x02\n" +
	"\x14GRPCInferenceService\x12>\n" +
	"\x05Infer\x12\x17.inference.InferRequest\x1a\x18.inference.InferResponse\"\x000\x01\x12F\n" +
	"\vInferStream\x12\x17.inference.InferRequest\x1a\x18.inference.InferResponse\"\x00(\x010\x01\x12M\n" +
	"\n" +
	"FetchInfer\x12\x1c.inference.FetchInferRequest\x1a\x1d.inference.FetchInferResponse\"\x000\x01\x12J\n" +
	"\fSendResponse\x12\x1e.inference.SendResponseRequest\x1a\x16.google.protobuf.Empty\"\x00(\x01B(Z&github.com/anyserve/anyserve/pkg/protob\x06proto3"

var (
	file_grpc_service_proto_rawDescOnce sync.Once
	file_grpc_service_proto_rawDescData []byte
)

func file_grpc_service_proto_rawDescGZIP() []byte {
	file_grpc_service_proto_rawDescOnce.Do(func() {
		file_grpc_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_service_proto_rawDesc), len(file_grpc_service_proto_rawDesc)))
	})
	return file_grpc_service_proto_rawDescData
}

var file_grpc_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_grpc_service_proto_goTypes = []any{
	(*InferCore)(nil),           // 0: inference.InferCore
	(*InferRequest)(nil),        // 1: inference.InferRequest
	(*InferResponse)(nil),       // 2: inference.InferResponse
	(*FetchInferRequest)(nil),   // 3: inference.FetchInferRequest
	(*FetchInferResponse)(nil),  // 4: inference.FetchInferResponse
	(*SendResponseRequest)(nil), // 5: inference.SendResponseRequest
	nil,                         // 6: inference.InferCore.MetadataEntry
	nil,                         // 7: inference.FetchInferRequest.MetadataEntry
	nil,                         // 8: inference.SendResponseRequest.MetricsEntry
	(*emptypb.Empty)(nil),       // 9: google.protobuf.Empty
}
var file_grpc_service_proto_depIdxs = []int32{
	6,  // 0: inference.InferCore.metadata:type_name -> inference.InferCore.MetadataEntry
	0,  // 1: inference.InferRequest.infer:type_name -> inference.InferCore
	0,  // 2: inference.InferResponse.response:type_name -> inference.InferCore
	7,  // 3: inference.FetchInferRequest.metadata:type_name -> inference.FetchInferRequest.MetadataEntry
	0,  // 4: inference.FetchInferResponse.infer:type_name -> inference.InferCore
	0,  // 5: inference.SendResponseRequest.response:type_name -> inference.InferCore
	8,  // 6: inference.SendResponseRequest.metrics:type_name -> inference.SendResponseRequest.MetricsEntry
	1,  // 7: inference.GRPCInferenceService.Infer:input_type -> inference.InferRequest
	1,  // 8: inference.GRPCInferenceService.InferStream:input_type -> inference.InferRequest
	3,  // 9: inference.GRPCInferenceService.FetchInfer:input_type -> inference.FetchInferRequest
	5,  // 10: inference.GRPCInferenceService.SendResponse:input_type -> inference.SendResponseRequest
	2,  // 11: inference.GRPCInferenceService.Infer:output_type -> inference.InferResponse
	2,  // 12: inference.GRPCInferenceService.InferStream:output_type -> inference.InferResponse
	4,  // 13: inference.GRPCInferenceService.FetchInfer:output_type -> inference.FetchInferResponse
	9,  // 14: inference.GRPCInferenceService.SendResponse:output_type -> google.protobuf.Empty
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_grpc_service_proto_init() }
func file_grpc_service_proto_init() {
	if File_grpc_service_proto != nil {
		return
	}
	file_grpc_service_proto_msgTypes[2].OneofWrappers = []any{}
	file_grpc_service_proto_msgTypes[4].OneofWrappers = []any{}
	file_grpc_service_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_service_proto_rawDesc), len(file_grpc_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_service_proto_goTypes,
		DependencyIndexes: file_grpc_service_proto_depIdxs,
		MessageInfos:      file_grpc_service_proto_msgTypes,
	}.Build()
	File_grpc_service_proto = out.File
	file_grpc_service_proto_goTypes = nil
	file_grpc_service_proto_depIdxs = nil
}
