# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import grpc_service_pb2 as grpc__service__pb2


class GRPCInferenceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Infer = channel.unary_stream(
                '/inference.GRPCInferenceService/Infer',
                request_serializer=grpc__service__pb2.InferRequest.SerializeToString,
                response_deserializer=grpc__service__pb2.InferResponse.FromString,
                _registered_method=True)
        self.InferStream = channel.stream_stream(
                '/inference.GRPCInferenceService/InferStream',
                request_serializer=grpc__service__pb2.InferRequest.SerializeToString,
                response_deserializer=grpc__service__pb2.InferResponse.FromString,
                _registered_method=True)
        self.FetchInfer = channel.unary_stream(
                '/inference.GRPCInferenceService/FetchInfer',
                request_serializer=grpc__service__pb2.FetchInferRequest.SerializeToString,
                response_deserializer=grpc__service__pb2.FetchInferResponse.FromString,
                _registered_method=True)
        self.SendResponse = channel.stream_unary(
                '/inference.GRPCInferenceService/SendResponse',
                request_serializer=grpc__service__pb2.SendResponseRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class GRPCInferenceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Infer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InferStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchInfer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendResponse(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GRPCInferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Infer': grpc.unary_stream_rpc_method_handler(
                    servicer.Infer,
                    request_deserializer=grpc__service__pb2.InferRequest.FromString,
                    response_serializer=grpc__service__pb2.InferResponse.SerializeToString,
            ),
            'InferStream': grpc.stream_stream_rpc_method_handler(
                    servicer.InferStream,
                    request_deserializer=grpc__service__pb2.InferRequest.FromString,
                    response_serializer=grpc__service__pb2.InferResponse.SerializeToString,
            ),
            'FetchInfer': grpc.unary_stream_rpc_method_handler(
                    servicer.FetchInfer,
                    request_deserializer=grpc__service__pb2.FetchInferRequest.FromString,
                    response_serializer=grpc__service__pb2.FetchInferResponse.SerializeToString,
            ),
            'SendResponse': grpc.stream_unary_rpc_method_handler(
                    servicer.SendResponse,
                    request_deserializer=grpc__service__pb2.SendResponseRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inference.GRPCInferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('inference.GRPCInferenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GRPCInferenceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Infer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/inference.GRPCInferenceService/Infer',
            grpc__service__pb2.InferRequest.SerializeToString,
            grpc__service__pb2.InferResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InferStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/inference.GRPCInferenceService/InferStream',
            grpc__service__pb2.InferRequest.SerializeToString,
            grpc__service__pb2.InferResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchInfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/inference.GRPCInferenceService/FetchInfer',
            grpc__service__pb2.FetchInferRequest.SerializeToString,
            grpc__service__pb2.FetchInferResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendResponse(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/inference.GRPCInferenceService/SendResponse',
            grpc__service__pb2.SendResponseRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
