server:
  host: "0.0.0.0"
  port: 8848
  logger:
    fields:
      - method
      - path
      - status
  grpc:
    port: 50052
    tls_enabled: false
    cert_file: ""
    key_file: ""
queue:
  engine: "embedded_nats" # Available options: "embedded_nats", "nats", "redis"

embedded_nats:
  port: 4222
  store_dir: "/tmp/nats"

logger:
  level: "info"
  development: false
