// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: pkg/proto/grpc_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerReadyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerReadyRequest) Reset() {
	*x = ServerReadyRequest{}
	mi := &file_pkg_proto_grpc_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerReadyRequest) ProtoMessage() {}

func (x *ServerReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_grpc_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerReadyRequest.ProtoReflect.Descriptor instead.
func (*ServerReadyRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_grpc_service_proto_rawDescGZIP(), []int{0}
}

type ServerLiveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Live          bool                   `protobuf:"varint,1,opt,name=live,proto3" json:"live,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerLiveResponse) Reset() {
	*x = ServerLiveResponse{}
	mi := &file_pkg_proto_grpc_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerLiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerLiveResponse) ProtoMessage() {}

func (x *ServerLiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_grpc_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerLiveResponse.ProtoReflect.Descriptor instead.
func (*ServerLiveResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_grpc_service_proto_rawDescGZIP(), []int{1}
}

func (x *ServerLiveResponse) GetLive() bool {
	if x != nil {
		return x.Live
	}
	return false
}

type ServerLiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerLiveRequest) Reset() {
	*x = ServerLiveRequest{}
	mi := &file_pkg_proto_grpc_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerLiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerLiveRequest) ProtoMessage() {}

func (x *ServerLiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_grpc_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerLiveRequest.ProtoReflect.Descriptor instead.
func (*ServerLiveRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_grpc_service_proto_rawDescGZIP(), []int{2}
}

type ServerReadyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerReadyResponse) Reset() {
	*x = ServerReadyResponse{}
	mi := &file_pkg_proto_grpc_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerReadyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerReadyResponse) ProtoMessage() {}

func (x *ServerReadyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_grpc_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerReadyResponse.ProtoReflect.Descriptor instead.
func (*ServerReadyResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_grpc_service_proto_rawDescGZIP(), []int{3}
}

func (x *ServerReadyResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

var File_pkg_proto_grpc_service_proto protoreflect.FileDescriptor

const file_pkg_proto_grpc_service_proto_rawDesc = "" +
	"\n" +
	"\x1cpkg/proto/grpc_service.proto\x12\tinference\"\x14\n" +
	"\x12ServerReadyRequest\"(\n" +
	"\x12ServerLiveResponse\x12\x12\n" +
	"\x04live\x18\x01 \x01(\bR\x04live\"\x13\n" +
	"\x11ServerLiveRequest\"+\n" +
	"\x13ServerReadyResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready2\xb3\x01\n" +
	"\x14GRPCInferenceService\x12K\n" +
	"\n" +
	"ServerLive\x12\x1c.inference.ServerLiveRequest\x1a\x1d.inference.ServerLiveResponse\"\x00\x12N\n" +
	"\vServerReady\x12\x1d.inference.ServerReadyRequest\x1a\x1e.inference.ServerReadyResponse\"\x00B(Z&github.com/anyserve/anyserve/pkg/protob\x06proto3"

var (
	file_pkg_proto_grpc_service_proto_rawDescOnce sync.Once
	file_pkg_proto_grpc_service_proto_rawDescData []byte
)

func file_pkg_proto_grpc_service_proto_rawDescGZIP() []byte {
	file_pkg_proto_grpc_service_proto_rawDescOnce.Do(func() {
		file_pkg_proto_grpc_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_grpc_service_proto_rawDesc), len(file_pkg_proto_grpc_service_proto_rawDesc)))
	})
	return file_pkg_proto_grpc_service_proto_rawDescData
}

var file_pkg_proto_grpc_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_proto_grpc_service_proto_goTypes = []any{
	(*ServerReadyRequest)(nil),  // 0: inference.ServerReadyRequest
	(*ServerLiveResponse)(nil),  // 1: inference.ServerLiveResponse
	(*ServerLiveRequest)(nil),   // 2: inference.ServerLiveRequest
	(*ServerReadyResponse)(nil), // 3: inference.ServerReadyResponse
}
var file_pkg_proto_grpc_service_proto_depIdxs = []int32{
	2, // 0: inference.GRPCInferenceService.ServerLive:input_type -> inference.ServerLiveRequest
	0, // 1: inference.GRPCInferenceService.ServerReady:input_type -> inference.ServerReadyRequest
	1, // 2: inference.GRPCInferenceService.ServerLive:output_type -> inference.ServerLiveResponse
	3, // 3: inference.GRPCInferenceService.ServerReady:output_type -> inference.ServerReadyResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_grpc_service_proto_init() }
func file_pkg_proto_grpc_service_proto_init() {
	if File_pkg_proto_grpc_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_grpc_service_proto_rawDesc), len(file_pkg_proto_grpc_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_grpc_service_proto_goTypes,
		DependencyIndexes: file_pkg_proto_grpc_service_proto_depIdxs,
		MessageInfos:      file_pkg_proto_grpc_service_proto_msgTypes,
	}.Build()
	File_pkg_proto_grpc_service_proto = out.File
	file_pkg_proto_grpc_service_proto_goTypes = nil
	file_pkg_proto_grpc_service_proto_depIdxs = nil
}
