name: anyserve CI

on:
  push:
    branches: ["main"]
    paths:
      - "anyserve/**"
      - "api/**"
      - "Makefile"
      - ".github/workflows/anyserve-ci.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "anyserve/**"
      - "api/**"
      - "Makefile"
      - ".github/workflows/anyserve-ci.yml"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache: true

      - name: Install Buf
        uses: bufbuild/buf-setup-action@v1.50.0

      - name: Generate gRPC files
        run: make buf

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest
          working-directory: anyserve

      - name: Build
        run: make -C anyserve build

      - name: Test
        run: make -C anyserve test COVERAGE=1

      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          files: ./anyserve/coverage.txt
          token: ${{ secrets.CODECOV_TOKEN }}
