# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
        cache: true

    - name: Install Buf
      uses: bufbuild/buf-setup-action@v1.50.0
      run: buf --version

    - name: Lint
      run: go vet ./...

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

    - uses: codecov/codecov-action@v5
      with:
        fail_ci_if_error: true
        files: ./coverage.txt
        flags: unittests
        name: codecov-umbrella
        token: "2e86188e-66ed-48b1-9f3a-38a8d190cf9b"
        verbose: true